name: flutter_json_view
description: Displaying json models in a Flutter widget with customization.
version: 1.1.5
homepage: https://github.com/Frezyx/flutter_json_view

topics:
  - widget
  - ui
  - json
  - debug
  - inspector

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <4.0.0"
